# Docker image
# Build a Docker image to deploy, run, or push to a container registry.
# Add steps that use Docker Compose, tag images, push to a registry, run an image, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

pool:
  vmImage: 'Ubuntu 16.04'
variables:
  registryServerName: '$(registryName).azurecr.io'
  imageName: '$(projectName)'
  # define 4 more variables: tenantId, registryName, registryLogin and registryPassword in the build pipeline in UI
steps:
- bash: docker build -t $(registryServerName)/$(imageName):$(build.buildId) .  # add options to this command to meet your needs
  displayName: Docker Build
- bash: docker login $(registryServerName) -u $(containerUser) -p $(containerPwd)
  displayName: Docker Login
- bash: docker push $(registryServerName)/$(imageName):$(build.buildId)
  displayName: Push image to Azure Container Registry
